#!/bin/sh

GPIO_CHIP=$1
GPIO_PIN=$2
GPIO_ON=0
GPIO_OFF=1

gpio_set(){
    local chip=$1
    local gpio=$2
    local value=$3
    gpioset $chip $gpio=$value
    echo "Set $1 $2 $3"
}

main(){

    case $1 in
    on|ON)
        gpio_set $GPIO_CHIP $GPIO_PIN $GPIO_ON
        ;;
    off|OFF)
        gpio_set $GPIO_CHIP $GPIO_PIN $GPIO_OFF
        ;;
    0|1)  
        gpio_set $GPIO_CHIP $GPIO_PIN $1
        ;;
    *)  echo "Invalid parameter"
        ;;
    esac

}
echo "IN $1 $2 $3"
main $3